entries:
  - "136.199.51.110	ssds110.dbnet.syssoft.uni-trier.de"
  - "136.199.51.111	ssds111.dbnet.syssoft.uni-trier.de"
  - "136.199.51.112	ssds112.dbnet.syssoft.uni-trier.de"
  - "136.199.51.113	ssds113.dbnet.syssoft.uni-trier.de"
  - "136.199.51.114	ssds114.dbnet.syssoft.uni-trier.de"
  - "136.199.51.115	ssds115.dbnet.syssoft.uni-trier.de"
  - "136.199.51.116	ssds116.dbnet.syssoft.uni-trier.de"
  - "136.199.51.117	ssds117.dbnet.syssoft.uni-trier.de"
  - "136.199.51.118	ssds118.dbnet.syssoft.uni-trier.de"
  - "136.199.51.119	ssds119.dbnet.syssoft.uni-trier.de"
